export const DEMO_PLEKJES = [
  {
    id: "1",
    name: "Café de Klos",
    neighborhood: "Jordaan",
    imageUrl: null,
    tags: [
      { emoji: "👯", name: "Met vrienden" },
      { emoji: "🍕", name: "Casual eten" },
      { emoji: "🍻", name: "Gezellig borrelen" },
    ],
    scoutName: "Patrick",
    scoutTitle: "Lekker ventje",
  },
  {
    id: "2",
    name: "Pluk",
    neighborhood: "Centrum",
    imageUrl: null,
    tags: [
      { emoji: "💕", name: "Date" },
      { emoji: "☕", name: "Koffie & taart" },
      { emoji: "📸", name: "Instagrammable" },
      { emoji: "🌿", name: "Binnentuin" },
    ],
    scoutName: "Lisa",
    scoutTitle: "Lekker grietje",
  },
  {
    id: "3",
    name: "Hannekes Boom",
    neighborhood: "Centrum",
    imageUrl: null,
    tags: [
      { emoji: "☀️", name: "In de zon" },
      { emoji: "🌊", name: "Aan het water" },
      { emoji: "🍻", name: "Gezellig borrelen" },
      { emoji: "🐕", name: "Hond mee" },
    ],
    scoutName: "Jaap",
    scoutTitle: "Lekker ventje",
  },
  {
    id: "4",
    name: "Bak Restaurant",
    neighborhood: "Noord",
    imageUrl: null,
    tags: [
      { emoji: "🥂", name: "Fancy dineren" },
      { emoji: "💕", name: "Date" },
      { emoji: "🌊", name: "Aan het water" },
    ],
    scoutName: "Sanne",
    scoutTitle: "Toppertje",
  },
  {
    id: "5",
    name: "Dignita Hoftuin",
    neighborhood: "Plantage",
    imageUrl: null,
    tags: [
      { emoji: "🥞", name: "Ontbijt / brunch" },
      { emoji: "🌿", name: "Binnentuin" },
      { emoji: "👨‍👩‍👦", name: "Met je ouders" },
      { emoji: "🤫", name: "Rustig" },
    ],
    scoutName: "Eva",
    scoutTitle: "Lekker grietje",
  },
  {
    id: "6",
    name: "Bar Botanique",
    neighborhood: "Oost",
    imageUrl: null,
    tags: [
      { emoji: "🍹", name: "Pre-drinks" },
      { emoji: "🌿", name: "Binnentuin" },
      { emoji: "📸", name: "Instagrammable" },
    ],
    scoutName: "Daan",
    scoutTitle: "Lekker ventje",
  },
];
