export const DEMO_PLEKJES = [
  {
    id: "1",
    name: "Café de Klos",
    neighborhood: "Jordaan",
    imageUrl: null,
    tags: [
      { emoji: "👯", name: "Met vrienden" },
      { emoji: "🍕", name: "Casual eten" },
      { emoji: "🍺", name: "Biertje doen" },
    ],
    scoutName: "Patrick",
    scoutTitle: "Lekker ventje",
  },
  {
    id: "2",
    name: "Pluk",
    neighborhood: "Centrum",
    imageUrl: null,
    tags: [
      { emoji: "💕", name: "Date" },
      { emoji: "☕", name: "Koffie" },
      { emoji: "🥞", name: "Ontbijt / brunch" },
    ],
    scoutName: "Lisa",
    scoutTitle: "Lekker grietje",
  },
  {
    id: "3",
    name: "Hannekes Boom",
    neighborhood: "Centrum",
    imageUrl: null,
    tags: [
      { emoji: "☀️", name: "Terrasje pakken" },
      { emoji: "🍺", name: "Biertje doen" },
      { emoji: "👯", name: "Met vrienden" },
    ],
    scoutName: "Jaap",
    scoutTitle: "Lekker ventje",
  },
  {
    id: "4",
    name: "Bak Restaurant",
    neighborhood: "Noord",
    imageUrl: null,
    tags: [
      { emoji: "🍽️", name: "Diner" },
      { emoji: "💕", name: "Date" },
      { emoji: "🍸", name: "Cocktails" },
    ],
    scoutName: "Sanne",
    scoutTitle: "Toppertje",
  },
  {
    id: "5",
    name: "Dignita Hoftuin",
    neighborhood: "Plantage",
    imageUrl: null,
    tags: [
      { emoji: "🥞", name: "Ontbijt / brunch" },
      { emoji: "👨‍👩‍👦", name: "Met je ouders" },
      { emoji: "☕", name: "Koffie" },
    ],
    scoutName: "Eva",
    scoutTitle: "Lekker grietje",
  },
  {
    id: "6",
    name: "Bar Botanique",
    neighborhood: "Oost",
    imageUrl: null,
    tags: [
      { emoji: "🍹", name: "Pre-drinks" },
      { emoji: "🍸", name: "Cocktails" },
      { emoji: "💕", name: "Date" },
    ],
    scoutName: "Daan",
    scoutTitle: "Lekker ventje",
  },
];
